### ISSUE TITLE
Add list of applications using this library

### ISSUE THREAD

**Issue by PanderMusubi** [ericfarng/jid3lib#1]
Please, add to the README.md file a list of applications using this library.

**Comment by ericfarng** [comment]
Done. Is that what you're looking for? Thank you for the suggestion.

**Comment by PanderMusubi** [comment]
Thanks. But these aren't bulk/GUI tools?

**Comment by ericfarng** [comment]
Oh I see. I've put some links to some apps that I could find. Is that what you're looking for?

**Comment by PanderMusubi** [comment]
Yes, thanks
